name: Check DMV website

on:
  schedule:
    - cron: '*/5 5-18 * * *'  # Runs every 5 minutes from 5 AM to 7 PM UTC
  workflow_dispatch:  # Allows you to manually trigger the workflow


jobs:
  selenium:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out your repository content

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'  

    - name: Install dependencies
      run: |
        pip install selenium requests
        sudo apt-get install -y chromium-chromedriver
        sudo apt-get install -y chromium-browser
        sudo Xvfb :99 -ac &  # Start virtual display


    - name: Run the script
      run: |
        DISPLAY=:99 python hqb.py  # Run the script with headless Chromium
